apiVersion: v1
kind: Namespace
metadata:
  name: webshop
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-management
---
apiVersion: v1
kind: Namespace
metadata:
  name: warehouse
---
apiVersion: v1
kind: Namespace
metadata:
  name: order-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
