apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: webshop
type: Opaque
data:
  # user: postgres, password: password (base64 encoded)
  username: cG9zdGdyZXM=
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: product-management
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: warehouse
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: order-service
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cGFzc3dvcmQ=
